### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [ToothedTomb/RustFetch#1]
Hi. What license applies to this project? It looks good already and also great to learn from for improving my Rust skills :)

**Comment by ToothedTomb** [comment]
This project is open source and this means you can modify the code / use the code as much as you want for free.
Hope you have a great time improving your Rust skills. :) 

Thanks Jonathan Steadman

**Comment by LifeCANvs** [comment]
> This project is open source and this means you can modify the code / use the code as much as you want for free. Hope you have a great time improving your Rust skills. :)
> 
> Thanks Jonathan Steadman

Hi. Thanks, so does that mean it is like the MIT license? Of course if I ever use any of your code, I will definitely credit you!

**Comment by ToothedTomb** [comment]
Yes its more like the MIT license. Feel free to use my code. 

Thanks Jonathan Steadman.
